"""Add sessions table

Revision ID: 840b7b5a17d4
Revises: 7fe87400c96f
Create Date: 2025-03-28 14:06:54.621926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840b7b5a17d4'
down_revision = '7fe87400c96f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    # ### end Alembic commands ###
